sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules
env:
  - DISPLAY=:99.0

before_install:
  - "npm prune"

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "npm ls"

script: 
  - "npm test"

after_success:

branches:
  only:
    - master
